---
- name: Gather facts and save archive
  hosts: target_server
  gather_facts: yes
  gather_subset:
    - "!all"
    - min
    - network
    - hardware
  become: false

  tasks:
    - name: Ensure local archive folder exists
      file:
        path: "/opt/ansible/facts"
        state: directory
        mode: '0750'
      delegate_to: localhost

    - name: Save facts archive
      copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: "/opt/ansible/facts/{{ inventory_hostname }}.json"
        mode: '0640'
      delegate_to: localhost